voices:
  profeinstein:
    cs-CZ: azure:cs-CZ-AntoninNeural
    en-US: acapela:Will22k_HQ
    en: acapela:Will22k_HQ
    ko-KR: azure:ko-KR-InJoonNeural
    ko: azure:ko-KR-InJoonNeural
  sophia:
    # For other languages see https://docs.aws.amazon.com/polly/latest/dg/voicelist.html
    ar-SA: polly:Zeina
    cmn-Hans-CN: polly:Zhiyu
    cs-CZ: azure:cs-CZ-VlastaNeural
    de-DE: polly:Vicki
    en-US: cereproc:audrey
    es-ES: polly:Conchita # Enrique
    fr-FR: polly:Celine
    hi-IN: polly:Aditi
    hu-HU: azure:hu-HU-NoemiNeural
    it-IT: polly:Bianca
    ja-JP: polly:Mizuki
    ko-KR: polly:Seoyeon
    nb-NO: azure:nb-NO-IselinNeural
    pl-PL: polly:Ewa
    ru-RU: polly:Tatyana
    yue-Hant-HK: polly:Hiujin
  littlesophia:
    #en-US: acapela:Ella22k_HQ
    en-US: polly:Ivy
  grace:
    # For other languages see https://docs.aws.amazon.com/polly/latest/dg/voicelist.html
    ar-SA: polly:Zeina
    cmn-Hans-CN: polly:Zhiyu
    de-DE: polly:Vicki
    en-US: polly:Salli
    es-ES: polly:Conchita
    fr-FR: polly:Celine
    hi-IN: polly:Aditi
    it-IT: polly:Bianca
    ja-JP: polly:Mizuki
    ko-KR: polly:Seoyeon
    ru-RU: polly:Tatyana
    yue-Hant-HK: azure:zh-HK-HiuMaanNeural # https://docs.microsoft.com/azure/cognitive-services/speech-service/language-support#text-to-speech
mappings:
  azure: # https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-speech-synthesis-viseme?pivots=programming-language-python#map-phonemes-to-visemes
    A-I: ['4', '1', '2', '3', '11', '9']
    C-D-G-K-N-S-TH: ['17', '15', '16']
    E: ['6', '5', '19', '20', '12']
    F-V: ['18']
    L: ['14']
    M: ['21', ]
    O: ['8', '10']
    Q-W: ['7']
    Sil: ['0']
    U: ['13']
  acapela:
    A-I: [4, 1, 2, 3, 11, 9]
    C-D-G-K-N-S-TH: [17, 15, 16]
    E: [6, 5, 19, 20, 12]
    F-V: [18]
    L: [14]
    M: [21]
    O: [8, 10]
    Q-W: [7]
    Sil: [0]
    U: [13]
  cereproc:
    A-I: [a, aa, ai, au, ae, ah, aw, ax, ay, ey, aeh, an, ah1, ax2, ae1]
    C-D-G-K-N-S-TH: [ch, d, dh, g, h, hh, jh, k, n, ng, s, sh, t, th, z, zh, dx, er, dzh, tsh, ts]
    E: [e, e@, ei, ii, iy, ei, eh, x, en, uw1, ow2, er1]
    F-V: [f, v, rv]
    L: ['@', '@@', i, i@, ih, l, r, y, R, rl]
    M: [b, m, p, pf]
    O: [o, oi, oo, ou, ao, ow, oy, oh, oe, oeh, 'on', oen]
    Q-W: [w, q]
    Sil: [sil]
    U: [u, u@, uh, uu, uw, j, ue, ueh]
  pinyin:
    A-I: [a, ai, ao, an, ang]
    C-D-G-K-N-S-TH: [ch, d, g, h, k, n, s, sh, z, zh, j, c]
    E: [e, ei, er, en, eng, t, x, ia, iao, iou, ian, iang, i, iu, ie, in, ing, iong, y]
    F-V: [f]
    L: [l, r]
    M: [b, m, p]
    O: [o, uo, ou, ong]
    Q-W: [w]
    Sil: [sil]
    U: [u, ui, un, v, ve, ue, vn, q, ua, uai, uan, van, uang, uei, uen, ueng]
  polly:
    A-I: [a, '@', E]
    C-D-G-K-N-S-TH: [k, s, S, T]
    E: [e, t, i]
    F-V: [f]
    L: [l, r]
    M: [p, B]
    O: [O]
    Q-W: [w]
    Sil: [sil, ""]
    U: [u, J, o]
  polly_full:
    polly_a: [a]
    polly_at: ['@']
    polly_e: [e]
    polly_ee: [E]
    polly_f: [f]
    polly_i: [i]
    polly_jj: [J]
    polly_k: [k]
    polly_l: [l]
    polly_o: [o]
    polly_oo: [O]
    polly_p: [p]
    polly_r: [r]
    polly_s: [s]
    polly_sil: [sil]
    polly_ss: [S]
    polly_t: [t]
    polly_tt: [T]
    polly_u: [u]
    polly_w: [w]
  snet:
    A-I: [a, '@', E]
    C-D-G-K-N-S-TH: [k, s, S, T]
    E: [e, t, i]
    F-V: [f]
    L: [l, r]
    M: [p, B]
    O: [O]
    Q-W: [w]
    Sil: [sil, ""]
    U: [u, J, o]
params:
  cereproc:
    A-I: {duration: 1.5, magnitude: 0.99, rampin: 0.2, rampout: 0.2}
    C-D-G-K-N-S-TH: {duration: 1.5, magnitude: 0.99, rampin: 0.2, rampout: 0.2}
    E: {duration: 1.6, magnitude: 0.99, rampin: 0.2, rampout: 0.2}
    F-V: {duration: 1.5, magnitude: 0.99, rampin: 0.2, rampout: 0.2}
    L: {duration: 1.5, magnitude: 0.99, rampin: 0.2, rampout: 0.2}
    M: {duration: 1.2, magnitude: 0.99, rampin: 0.2, rampout: 0.2}
    O: {duration: 1.5, magnitude: 0.99, rampin: 0.2, rampout: 0.2}
    Q-W: {duration: 1.5, magnitude: 0.99, rampin: 0.2, rampout: 0.2}
    Sil: {duration: 1.0, magnitude: 0.99, rampin: 0.2, rampout: 0.2}
    U: {duration: 1.8, magnitude: 0.99, rampin: 0.3, rampout: 0.2}
  polly:
    A-I: {duration: 1.2, magnitude: 0.99, rampin: 0.2, rampout: 0.2}
    C-D-G-K-N-S-TH: {duration: 1.5, magnitude: 0.99, rampin: 0.2, rampout: 0.2}
    E: {duration: 1.2, magnitude: 0.99, rampin: 0.2, rampout: 0.2}
    F-V: {duration: 1.5, magnitude: 0.99, rampin: 0.2, rampout: 0.2}
    L: {duration: 1.5, magnitude: 0.99, rampin: 0.2, rampout: 0.2}
    M: {duration: 1.0, magnitude: 0.99, rampin: 0.2, rampout: 0.2}
    O: {duration: 1.2, magnitude: 0.99, rampin: 0.2, rampout: 0.2}
    Q-W: {duration: 1.5, magnitude: 0.99, rampin: 0.2, rampout: 0.2}
    Sil: {duration: 1.0, magnitude: 0.99, rampin: 0.2, rampout: 0.2}
    U: {duration: 1.2, magnitude: 0.99, rampin: 0.3, rampout: 0.2}
  azure:
    A-I: {duration: 2.0, magnitude: 0.99, rampin: 0.2, rampout: 0.2}
    C-D-G-K-N-S-TH: {duration: 1.5, magnitude: 0.99, rampin: 0.2, rampout: 0.2}
    E: {duration: 1.8, magnitude: 0.99, rampin: 0.2, rampout: 0.2}
    F-V: {duration: 1.5, magnitude: 0.99, rampin: 0.2, rampout: 0.2}
    L: {duration: 1.5, magnitude: 0.99, rampin: 0.2, rampout: 0.2}
    M: {duration: 1.0, magnitude: 0.99, rampin: 0.2, rampout: 0.2}
    O: {duration: 1.8, magnitude: 0.99, rampin: 0.2, rampout: 0.2}
    Q-W: {duration: 1.5, magnitude: 0.99, rampin: 0.2, rampout: 0.2}
    Sil: {duration: 1.0, magnitude: 0.99, rampin: 0.2, rampout: 0.2}
    U: {duration: 1.8, magnitude: 0.99, rampin: 0.3, rampout: 0.2}
  polly_full:
    polly_a: {duration: 2.2, magnitude: 0.99, rampin: 0.35, rampout: 0.25}
    polly_at: {duration: 2.2, magnitude: 0.99, rampin: 0.35, rampout: 0.25}
    polly_e: {duration: 2.5, magnitude: 0.99, rampin: 0.4, rampout: 0.25}
    polly_ee: {duration: 2.2, magnitude: 0.99, rampin: 0.35, rampout: 0.25}
    polly_f: {duration: 1.0, magnitude: 0.99, rampin: 0.25, rampout: 0.25}
    polly_i: {duration: 2.5, magnitude: 0.99, rampin: 0.4, rampout: 0.25}
    polly_jj: {duration: 2.0, magnitude: 0.99, rampin: 0.35, rampout: 0.25}
    polly_k: {duration: 1.5, magnitude: 0.99, rampin: 0.35, rampout: 0.25}
    polly_l: {duration: 1.0, magnitude: 0.99, rampin: 0.25, rampout: 0.25}
    polly_o: {duration: 2.0, magnitude: 0.99, rampin: 0.35, rampout: 0.25}
    polly_oo: {duration: 2.3, magnitude: 0.99, rampin: 0.4, rampout: 0.25}
    polly_p: {duration: 1.2, magnitude: 0.99, rampin: 0.35, rampout: 0.25}
    polly_r: {duration: 1.0, magnitude: 0.99, rampin: 0.25, rampout: 0.25}
    polly_s: {duration: 1.5, magnitude: 0.99, rampin: 0.35, rampout: 0.25}
    polly_sil: {duration: 2.0, magnitude: 0.99, rampin: 0.35, rampout: 0.25}
    polly_ss: {duration: 1.5, magnitude: 0.99, rampin: 0.35, rampout: 0.25}
    polly_t: {duration: 2.5, magnitude: 0.99, rampin: 0.4, rampout: 0.25}
    polly_tt: { duration: 1.5, magnitude: 0.99, rampin: 0.35, rampout: 0.25}
    polly_u: {duration: 2.0, magnitude: 0.99, rampin: 0.35, rampout: 0.25}
    polly_w: {duration: 1.0, magnitude: 0.99, rampin: 0.25, rampout: 0.25}

# Mouth edges up <MO=CH,0,1>
# Mouth edges default <MO=CH,0.5,1>
# Mouth edges down<MO=CH,1,1>
# Mouth close <MO=MO,0,1>
# Mouth open <MO=MO,1,1>
#lip_motor_mappings:
#    1: '<MO=MO,0.5,0.1><PA><MO=MO,0.1,0.1>'
#    2: '<MO=MO,0.4,0.1><PA><MO=MO,0.1,0.1>'
#    Sil: '<MO=MO,0,{speed}>'

lip_motor_mappings:
  profeinstein:
    A-I: '<MO=MO,0.5,{speed}><MO=CH,0.5,{speed}>'
    C-D-G-K-N-S-TH: '<MO=MO,0.3,{speed}><MO=CH,0.2,{speed}>'
    E: '<MO=MO,0.3,{speed}><MO=CH,0,{speed}>'
    F-V: '<MO=MO,{speed},{speed}><MO=CH,0.7,{speed}>'
    L: '<MO=MO,0.4,{speed}><MO=CH,0,{speed}>'
    M: '<MO=MO,0,{speed}><MO=CH,0.6,{speed}>'
    O: '<MO=MO,0.6,{speed}><MO=CH,0.5,{speed}>'
    Q-W: '<MO=MO,0.4,{speed}><MO=CH,0.5,{speed}>'
    Sil: '<MO=MO,0,{speed}><MO=CH,0.5,{speed}>'
    U: '<MO=MO,0.2,{speed}><MO=CH,0.5,{speed}>'
