mappings:
  cereproc:
    A-I: [a, aa, ai, au, ae, ah, aw, ax, ay, ey, aeh, an, ah1, ax2, ae1]
    C-D-G-K-N-S-TH: [ch, d, dh, g, h, hh, jh, k, n, ng, s, sh, t, th, z, zh, dx, er, dzh, tsh, ts]
    E: [e, e@, ei, ii, iy, ei, eh, x, en, uw1, ow2, er1]
    F-V: [f, v, rv]
    L: ['@', '@@', i, i@, ih, l, r, y, R, rl]
    M: [b, m, p, pf]
    O: [o, oi, oo, ou, ao, ow, oy, oh, oe, oeh, 'on', oen]
    Q-W: [w, q]
    Sil: [sil]
    U: [u, u@, uh, uu, uw, j, ue, ueh]
  azure: # https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-speech-synthesis-viseme?pivots=programming-language-python#map-phonemes-to-visemes
    A-I: ['4', '1', '2', '3', '11', '9']
    C-D-G-K-N-S-TH: ['17', '15', '16']
    E: ['6', '5', '19', '20', '12']
    F-V: ['18']
    L: ['14']
    M: ['21', ]
    O: ['8', '10']
    Q-W: ['7']
    Sil: ['0']
    U: ['13']
  polly:
    A-I: [a, '@', E]
    C-D-G-K-N-S-TH: [k, s, S, T]
    E: [e, t, i]
    F-V: [f]
    L: [l, r]
    M: [p, B]
    O: [O]
    Q-W: [w]
    Sil: [sil, ""]
    U: [u, J, o]
  acapela:
    A-I: [4, 1, 2, 3, 11, 9]
    C-D-G-K-N-S-TH: [17, 15, 16]
    E: [6, 5, 19, 20, 12]
    F-V: [18]
    L: [14]
    M: [21]
    O: [8, 10]
    Q-W: [7]
    Sil: [0]
    U: [13]

# Mouth edges up <MO=CH,0,1>
# Mouth edges default <MO=CH,0.5,1>
# Mouth edges down<MO=CH,1,1>
# Mouth close <MO=MO,0,1>
# Mouth open <MO=MO,1,1>
#lip_motor_mappings:
#    1: '<MO=MO,0.5,0.1><PA><MO=MO,0.1,0.1>'
#    2: '<MO=MO,0.4,0.1><PA><MO=MO,0.1,0.1>'
#    Sil: '<MO=MO,0,{speed}>'

lip_motor_mappings:
    A-I: '<MO=MO,0.5,{speed}><MO=CH,0.5,{speed}>'
    C-D-G-K-N-S-TH: '<MO=MO,0.3,{speed}><MO=CH,0.2,{speed}>'
    E: '<MO=MO,0.3,{speed}><MO=CH,0,{speed}>'
    F-V: '<MO=MO,{speed},{speed}><MO=CH,0.7,{speed}>'
    L: '<MO=MO,0.4,{speed}><MO=CH,0,{speed}>'
    M: '<MO=MO,0,{speed}><MO=CH,0.6,{speed}>'
    O: '<MO=MO,0.6,{speed}><MO=CH,0.5,{speed}>'
    Q-W: '<MO=MO,0.4,{speed}><MO=CH,0.5,{speed}>'
    Sil: '<MO=MO,0,{speed}><MO=CH,0.5,{speed}>'
    U: '<MO=MO,0.2,{speed}><MO=CH,0.5,{speed}>'
